In [1]:
import numpy as np

## DataTypes & Attributes 

In [3]:
# NumPy's main datatype is ndarray (n dimensional array) 
a1 = np.array([1 , 2 , 3 ])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [30]:
a2 = np.array([[1 , 2.4 , 3],
             [4 , 5 , 6.5]])

a3 = np.array([[[1 , 3 , 3 ],
               [3 , 5 , 6],
               [3 , 5 , 6],
                [3 , 5 , 6]],
               
              [[10 , 11 , 12],
              [13 , 14 , 15],
               [16 , 17 , 18],
               [3 , 5 , 6]]])

In [31]:
a2

array([[1. , 2.4, 3. ],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  3,  3],
        [ 3,  5,  6],
        [ 3,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
 a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim

1

In [14]:
a3.ndim

3

In [15]:
a2.ndim

2

In [16]:
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

## whatever data you're working with, it somehow gets turned into numbers and then a machine learning algorithm will find patterns in these numbers 

In [17]:
a1.dtype , a2.dtype , a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [18]:
a1.size , a2.size , a3.size

(3, 6, 18)

In [19]:
type(a1) , type(a2) , type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [24]:
#so now to really exemplify Numpy being the backbone of other scientific data packages, that is  let's 
#create a dataframe form a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.4  3.0
1  4.0  5.0  6.5

So this is a pandas dataframe and this is our numpy array.
‫So essentially, no matter what's in our pandas dataframe, if it's all numbers, pandas is built on
‫top of numpy
‫So to represent our data as a data frame, it's just combining NumPy arrays in a formatted way.
‫So that's a very important point to remember as well, is that once we start to get into the weeds of
NumPy and start to work out what kind of numerical computing it can do, we can start to think, okay,

so if we have some data and we import it in PANDAS, it's actually just a different combination umpire
‫raise.
‫So if we want to perform some manipulations on it, we're actually just performing manipulations on
‫different lists of numbers.
‫All right.
‫That's a brief introduction to NumPy, his main data type.
‫That's the main thing to take away from this is that Andhra, whatever array you have in numpy is of
‫type NDI array and that pandas and other machine learning algorithm packages are built on top of numpy
‫and machine learning is finding patterns in numpy arrays.
‫So with that being said, let's take a little break.
‫If you need to go back and explore, create an array of your own by trialing it out.
‫If in doubt, run the code and I'll see you in the next video.



so if we have some data and we import it in PANDAS, it's actually just a different combination umpire
‫raise.
‫So if we want to perform some manipulations on it, we're actually just performing manipulations on
‫different lists of numbers.
‫All right.
‫That's a brief introduction to NumPy, his main data type.
‫That's the main thing to take away from this is that Andhra, whatever array you have in numpy is of
‫type NDI array and that pandas and other machine learning algorithm packages are built on top of numpy
‫and machine learning is finding patterns in numpy arrays.
‫So with that being said, let's take a little break.
‫If you need to go back and explore, create an array of your own by trialing it out.
‫If in doubt, run the code and I'll see you in the next video.


NumPy is called the "backbone" of the scientific Python ecosystem because it provides a powerful and efficient array object that forms the foundation for a wide variety of other libraries, including pandas, scikit-learn, and Matplotlib. These libraries build on top of the functionality provided by NumPy to provide powerful tools for data manipulation, analysis, and visualization. The array object in NumPy allows for fast, vectorized operations and is highly optimized for performance, making it well-suited for large-scale data processing and scientific computing tasks.

In my previous answer, when I said "NumPy provides a powerful and efficient array object that forms the foundation for a wide variety of other libraries," I meant that the array object in NumPy is used as the basis for many other libraries in the scientific Python ecosystem. These other libraries build on top of the functionality provided by NumPy to provide additional features and tools for data manipulation, analysis, and visualization. For example, pandas uses NumPy arrays as the underlying data structure for its DataFrame and Series objects, which provide additional methods for working with data in a tabular format. Similarly, scikit-learn uses NumPy arrays as the input for its machine learning algorithms, and Matplotlib uses NumPy arrays to represent and manipulate data for plotting and visualization. In short, NumPy is an important and widely used library that provides a powerful array object that is used as a foundation for many other libraries in the scientific Python ecosystem.

Yes, that's correct. The "ndarray," or "n-dimensional array," is the main data structure provided by NumPy and is used to store and manipulate large arrays of homogeneous data (i.e., data of the same type, such as integers or floating-point numbers). The "n" in "ndarray" refers to the fact that these arrays can have any number of dimensions, not just one or two as in traditional arrays. The ndarray is a universal array meaning it can handle a wide variety of data types, such as integers, floating-point numbers, and complex numbers, and can be used for a wide range of tasks, including mathematical and statistical operations, linear algebra, and data manipulation and transformation. The ndarray is highly optimized for performance, making it well-suited for large-scale data processing and scientific computing tasks.

##Anatomy of NumPy array

In [48]:
check1 = np.array([1 , 2 , 3])

In [49]:
check1.ndim

1

In [50]:
check2 = np.array([[1 , 2 , 4],
                  [3 , 5 ,5],
                  [4 , 5 ,5]])

In [51]:
check2.ndim

2

In [57]:


check3 = np.array([
    [
        [1 , 3 , 4],
         [1 , 3 , 4],
         [1 , 3 , 4]
    ],
     [
        [1 , 3 , 4],
         [1 , 3 , 4],
         [1 , 3 , 4]
    ],
     [
        [1 , 3 , 4],
         [1 , 3 , 4],
         [1 , 3 , 4]
    ],
      [
        [1 , 3 , 4],
         [1 , 3 , 4],
         [1 , 3 , 4]
    ]
    
])

In [62]:
check3.ndim

3

In [55]:
type(check1)

numpy.ndarray

In [64]:
check3.shape

(3, 3, 3)

often time with machine learning algorithm your main focus will be making sure the shape of your data that goes into machine learning algorithm lines up with the other data that you're putting in as well as the output we will see in fututre secion  

#note axis = 0 refer to the number of rows axis = 1 refers to the number of column and the axis = n refers to the dimension that are beyond just rows and columns its very hard for us humans to visualise anything more than three dimesnions, but in numpy and with computer you could have as many ends as you want

In [66]:
#shortform

check3.dtype 

dtype('int32')

In [67]:
check3.shape

(3, 3, 3)

In [68]:
type(check1)

numpy.ndarray

In [69]:
check3.ndim

3

In [70]:
check3

array([[[1, 3, 4],
        [1, 3, 4],
        [1, 3, 4]],

       [[1, 3, 4],
        [1, 3, 4],
        [1, 3, 4]],

       [[1, 3, 4],
        [1, 3, 4],
        [1, 3, 4]]])

In [71]:
check3.size

27

In [85]:
t1 = np.array(
   
     [
        [1 , 3 , 4] , 
         [1 , 3 , 4] , 
         [1 , 3 , 4] , 
    ]
    
)

In [83]:
import pandas as pd 

In [86]:
dataframe = pd.DataFrame(t1)
dataframe

0  1  2
0  1  3  4
1  1  3  4
2  1  3  4