## 3. Fit the model/algorithm on our data and use it to make predictions

### 3.1 Fitting the model to the data

Different names for:
* `X` = features, features variables, data
* `y` = labels, targets, target variables

In [3]:
# Standard imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
# Get the data (be sure to click "raw") - https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/data/heart-disease.csv 
heart_disease = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [12]:
# Import the RandomForestClassifier estimator class
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
# Setup random seed
np.random.seed(42)

# Make the data
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instantiate Random Forest Classifier
clf = RandomForestClassifier(n_estimators=100)

# Fit the model to the data (training the machine learning model) the model is going to find pattern  here and during testing it going touse the pattern the model has learn and this is the crocks of all of the machine learning
clf.fit(X_train, y_train)

# Evaluate the Random Forest Classifier (use the patterns the model has learned)
clf.score(X_test, y_test)#making prediction on unseen data just use the previous patter and gving output and comparing to the y test and giving reuslt how accurate it predicts

0.8524590163934426

In [8]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [9]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [10]:
#so what does fit actually do well when we pass x and y it will callls the model  to gotthrough all of the example in x the training data in our case and see what x corresponding label y label  is and try to figure out patterns that leads differnet cobination of numbers here what leads to have 1 as a label or 0 as a label  in the case of bottom of this
y.tail()
#that is fit in a nutshell
#and how th ml model in our case random forest class how this does is going to be different depending upon the accoridng to the model you use and explaining the detials of each and every one would required a entire a text book or much longer video off course for now to be a practisinear to starting ml code the most important thing is remeber is simlar to how you will found out the pattern if you had inof time 
#you look at the feature varibale in x like age sex cp trestbps and you will see what differnet value of this lead to different values and why ? one for heart disease zero for not heart disease
#you can dive as deeper you want to actually figure what the random forest classifie does or reandom forest regressor does that may be the extension we will do in future
# for now thats the crucks so if you want to figure out what does the ml model does it takes some data find patterns and figure out in supervise learning it fiures out how does the pattern relate to the label 
#that in nut shell if you like you can deep dipe into  this model but not focusing on this course we are focusing on writing ml code rather then going to theroy

298    0
299    0
300    0
301    0
302    0
Name: target, dtype: int64

### 3.2 Make predictions using a machine learning model

2 ways to make predictions:
1. `predict()`
2. `predict_proba()`

finally we are going to use train machine learning models to make some predicitions this is were magic in ml really comes down to 

In [13]:
# Use a trained model to make predictions

#now what do you think what predict might need to take to predict someone have heart disease or not so important thing is what our ml model learn on and in our case it learn on this feature we have to pass the same actuall data on same format to make it work 
clf.predict([1 , 7 , 8 , 3 ,4]) #this doesn't work

C:\Users\Learn To Earn\Desktop\sample_project_1\Machine-Learning-Data-Science\env\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[1. 7. 8. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [14]:
X_test.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2

In [17]:
clf.predict(X_test) #our model has trained on the training data but it haven't seen the test data if we have to make prediction it has to be on the shape 

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [20]:
np.array(y_test)  #our prediction is in same label as our test label is 

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [22]:
# Compare predictions to truth labels to evaluate the model
y_preds = clf.predict(X_test)
np.mean(y_preds == y_test)#comparing prediction with the real y test value y_preds is the prediction and we have already the answer and now comparing the answer with the prediction 

0.8524590163934426

In [23]:
clf.score(X_test , y_test)   

0.8524590163934426

In [25]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_preds)

0.8524590163934426

In [27]:
#three ways to do exact same thing 

Make predictions with `predict_proba()` - use this if someone asks you "what's the probability your model is assigning to each prediction?"

In [28]:
# predict_proba() returns probabilities of a classification label 
clf.predict_proba(X_test[:5])
#predict_proba() returns probabilities of a classification label 
#so what this is it is making prediction on same data its returning the probability of lable being true instead of predicting directlylabel 

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [32]:
# Let's predict() on the same data..
clf.predict(X_test[:5])
#so what this is it is making prediction on same data its returning the probability of lable being true instead of predicting directlylabel

array([0, 1, 1, 0, 1], dtype=int64)

In [34]:
X_test[:5]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2

In [33]:
heart_disease["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

as you might have guess the predict method can be also used on regression aglorithm as well


`predict()` can also be used for regression models.

go to chapter 2 we have done this because the video maker have all the code and chpaters in one page so there for go to chapter 3


In [36]:
# Get California Housing dataset
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [37]:

housing_df = pd.DataFrame(housing["data"], columns=housing["feature_names"])
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [52]:
housing_df.head(10)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
5  4.0368      52.0  4.761658   1.103627       413.0  2.139896     37.85   
6  3.6591      52.0  4.931907   0.951362      1094.0  2.128405     37.84   
7  3.1200      52.0  4.797527   1.061824      1157.0  1.788253     37.84   
8  2.0804      42.0  4.294118   1.117647      1206.0  2.026891     37.84   
9  3.6912      52.0  4.970588   0.990196      1551.0  2.172269     37.84   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422  
5    -122.25   2.697  
6    -122.25   2.992  
7    -122.25   2.414  
8    -122.26   2.267  
9    -122.25   2.611

In [39]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

# Create the data
X = housing_df.drop("target", axis=1)
y = housing_df["target"]

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create model instance
model = RandomForestRegressor()#n_estimator=100 n estimator is set by default 100 by sckit you can put than to 1000 200 10 and with the random forest, agian, that just means how many little models are we using to create one ensemble model to predict on our data let it be default        
# Fit the model to the data
model.fit(X_train, y_train)

# Make predictions
y_preds = model.predict(X_test)

In [41]:
y_preds[:10]

array([0.49384  , 0.75494  , 4.9285964, 2.54316  , 2.33176  , 1.6525301,
       2.34323  , 1.66182  , 2.47489  , 4.8344779])

In [56]:
np.array(y_test[:10])

C:\Users\Learn To Earn\AppData\Local\Temp\ipykernel_932\25245348.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  np.array(y_test[:10])


array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   , 1.587  , 1.982  ,
       1.575  , 3.4    , 4.466  ])

In [57]:
#this looks quite similar to this 
#now we're going to have a look at more regression evaluation metrics in a second, but how ? might we evaluate our model our models's predictions, that is on the test data set so if you made some predictions on the test data set, how can we how do you think we could evaluate these ? well we can compare them because let's have a look at length of y preds, why preds and length of y test  
len(y_test)

4128

In [58]:
len(y_preds)

4128

In [62]:
#Compare the predictions to the truth
from sklearn.metrics import mean_absolute_error       #the average difference between the  predictive value and truth value          
mean_absolute_error(y_test , y_preds)

# we have use mean_abolute_error so this means that on average , mean is the same as average  on average, each one of our models prediction is 0.32 different to the actual test value now of course there may be some predictions that are more thatn this value there may be some predcitions that are less than this value, worse thatn the y test value or different to the test y value

0.32659871732073664

In [61]:
housing_df["target"]#so our model predictions y spread are on average 0.32 different  so it could be plus or minus this target value
#but that's how we make predictions with our sckit estimators or models, we can use the predict function and then later on we're going to see a bit more about how we evaluate those predictions
#remember the crux of evaluation is comparing our model's predictions to what it should have predicted now there are many different ways to do that 

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: target, Length: 20640, dtype: float64

welcome back last video we see how to fit the model and use it to make predictions on our data

just important as making prdictions evaluating those pridcition 